config/routes.rb
ToGather::Application.routes.draw do

  devise_scope :user do
    post    'registrations' => 'registrations#create', :as => 'register'
    post    'users' => 'registrations#create', :as => 'sign_up'
    post    'sessions' => 'sessions#create', :as => 'login'
    delete  'sessions' => 'sessions#destroy', :as => 'logout'
  end
  devise_for :users

  match '/events/notification', :controller => 'events', :action => 'notification'

  resources :calendar
  resources :events
  resources :replies
  resources :devices
  resources :comments
  
  resources :users do
    resources :events do
      resources :invitations do
        resources :replies
      end
    end
  end

  root :to =>"events#index"

end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :title, :location, :description, :emails
  has_many :choices
  has_many :invitations
  has_many :replies
  has_one :decision
  belongs_to :user

  acts_as_commentable
  
  scope :between, lambda {|start_time, end_time|
    { :conditions => ["start BETWEEN ? AND ?", Event.format_date(start_time), Event.format_date(end_time)] }
  }

  def self.format_date(date_time)
  	Time.at(date_time.to_i).to_formatted_s(:db)
  end

  def as_json(options = {})
  {
  	:id => self.id,
  	:title => self.title,
  	:description => self.description || "",
  	:start => self.start.rfc822,
  	:end => self.end.rfc822,
  	:allDay => self.all_day,
  	:recurring => false,
  	:url => Rails.application.routes.url_helpers.event_path(self),
  }
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	include ActionView::Helpers::DateHelper
	before_filter :authenticate_user!, :except => :show

	def index
		if !params['launch'].nil?
			I18n.locale = 'zh-CN'
			@events = {}
			current_user.events.each do |event|
				@events[event.id] = {'title' => event.title,
														 'time' => time_ago_in_words(event.created_at),
														 'is_closed' => event.is_closed
														}
			end
			I18n.locale = 'en'
		elsif !params['invited'].nil?			
			I18n.locale = 'zh-CN'
			@events = {}
			current_user.invitations.each do |invitation|
				@events[invitation.event.id] = {'title' => invitation.event.title, 
																				'time' => time_ago_in_words(invitation.event.created_at),
																				'is_closed' => invitation.event.is_closed
																			 }
			end
			I18n.locale = 'en'
		else
			@launched_events = current_user.events
			# @invited_events = []
			# current_user.invitations.each do |invitation|
			# 	@invited_events.push(invitation.event)
			# end

			@participated_events = []
			current_user.replies.each do |reply|
				unless @participated_events.include? reply.event
					@participated_events.push(reply.event)
				end
			end

			@launched_events.sort!{|a,b|b.updated_at <=> a.updated_at}
			# @invited_events.sort!{|a,b|b.updated_at <=> a.updated_at}
			@participated_events.sort!{|a,b|b.updated_at <=> a.updated_at}
		end

		respond_to do |format|
			format.html
			format.json { 
				if !params['launch'].nil? || !params['invited'].nil?
					render 				:status => 200,
												:json => 	{ :success => true,
																		:data => @events.to_json
																	}
				else 
					render :json => @events
				end
			}
		end
	end

	def show
		@event = Event.find(params[:id])

		invitations = @event.invitations
		@replies_count = @event.replies.count

		# wait for implement
		@comments_count = @event.root_comments.count

		@comments = @event.root_comments
		@comments.sort!{|a,b|b.updated_at <=> a.updated_at}

		@latest_activity = @event.updated_at

		@is_owner = current_user == @event.user

		@is_closed = @event.is_closed

		respond_to do |format|
			format.json {
				choices = {}
				@event.choices.each do |choice|
					names = []
					choice.replies.each do |reply|
						names.push(reply.name)
					end
					choices[choice.number] = {
						'time' => choice.start_time.strftime('%Y-%m-%d\n%I:%M%p'),
						'count' => choice.replies.size,
						'names' => names
					}
				end

				render  :status => 200,
				:json => 	{ :success => true,
										:data => { 'title' => @event.title,
															 'time' => @event.created_at.strftime('%Y-%m-%d'),
															 'description' => @event.description,
															 'choices' => choices
														 } 
									}
			}
			format.html
		end
	end

	def new
		@event = Event.new
	end

	def create
		event = Event.new
		event.title = params[:title]
		event.description = params[:description]
		event.location = params[:location]
		event.start = 1.day.ago
		event.end = Time.now
		event.all_day = false
		event.user = current_user
		event.emails = params[:emails]

		choices_count = params[:'choices-count'].to_i
		1.upto(choices_count) do |i|
			choice = event.choices.build
			choice.start_time = params["choice-start-"+i.to_s]
			choice.end_time = params["choice-end-"+i.to_s]
			choice.number = i
			choice.save
		end

		emails = params['emails']
		invitations_count = emails.split(',').length
		1.upto(invitations_count) do |i|
			invitation = event.invitations.build
			invitation.email = emails.split(',')[i-1]
			invitee = User.where(:email => emails.split(',')[i-1]).first
			if !invitee.nil?
				invitation.user = invitee
			end
			invitation.save
		end

		event.save

		#push notification to android end if user invited have device registered
		api_key = 'AIzaSyBjg1TQV-puS06AAREhRnkFj2edW6dPtoE'
		gcm = GCM.new(api_key)
		registration_ids = []
		options = {data: {}, collapse_key: "new invitation"}
		emails.split(',').each do |email|
			client = User.where(:email => email).first
			if !client.nil? && !client.device.nil?
				registration_ids.push(client.device.registration_id)
			end
		end
		if registration_ids.size > 0
			response = gcm.send_notification(registration_ids, options)
			Rails.logger.debug('debug::' + response.to_json)
		end

		if emails.strip.length != 0
			UserMailer.invite(current_user, emails, event.title, event.description, event_url(event)).deliver
		end

		respond_to do |format|
			format.json {
				render :status => 200,
						   :json   => { :success => true,
												    :info => "event created",
												    :data => { :id => event.id}
											    }
			}
			format.html {
				redirect_to event_path(event)
			}
		end
		
	end

	def update
		@event = Event.find(params[:id])

		#close poll
		if !params['is_closed'].nil?
			@event.is_closed = params['is_closed']

			if params['decision-count'].to_i > 0
				decisions = @event.build_decision
				@event.choices.each do |choice|
					if !params['decision-'+choice.number.to_s].nil?
						decisions.choices << choice
					end
				end
				decisions.save
			end

			@event.save

		#edit poll
		else
			@event.update_attributes(params[:event])
			emails = @event.emails
			emailList = []
			@event.invitations.each do |invitation|
				emailList.push(invitation.email)
			end
			newEmailList = @event.emails.split(',')
			sendList = ''
			newEmailList.each do |email|
				unless emailList.include? email
					sendList += email + ','

					invitation = @event.invitations.build
					invitation.email = email
					invitee = User.where(:email => email).first
					if !invitee.nil?
						invitation.user = invitee
					end
					invitation.save
				end
			end

			if sendList.strip.length != 0
			UserMailer.invite(current_user, sendList, @event.title, @event.description, event_url(@event)).deliver
		end


			choices_count = params[:'choices-count'].to_i
			choices = @event.choices
			index = 0
			count = choices.count
			1.upto(choices_count) do |i|
				start_time = params["choice-start-"+i.to_s]
				end_time = params["choice-end-"+i.to_s]
				
				while index < count && start_time > choices[index].start_time
					index += 1
				end

				unless index < count && !(start_time < choices[index].start_time)
					choice = @event.choices.build
					choice.start_time = start_time
					choice.end_time = end_time
					choices.insert(index, choice)
					count += 1
				end
			end

			1.upto(count) do |i|
				choices[i-1].number = i
				choices[i-1].save
			end
		end

		respond_to do |format|
			format.html {
				redirect_to event_path(@event)
			}
			format.json {
				render :status => 200,
						   :json   => { :success => true,
												    :data => {}
											    }
			}
		end
	end

	def edit
		@event = Event.find(params[:id])
	end

	def notification
		@reply_name = params[:reply_name]
		@event_id = params[:event_id]
	end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/edit.html.erb
<%= javascript_include_tag params[:controller] %>

<form id="edit_form" class="form" action="/events/<%= @event.id %>" method="post">
  <input type="hidden" value="put" name="_method">
  <div class="tabbable tabs-left">

    <ul class="nav nav-tabs">
      <li class="active"><a href="#General" data-toggle="tab">General</a></li>
      <li><a href="#Time" data-toggle="tab">Time</a></li>
      <li><a href="#Invite" data-toggle="tab">Invite</a></li>
    </ul>

    <div class="tab-content">

      <div class="tab-pane active" id="General">

        <legend>General information</legend>

        <label for="inputTitle">Title</label>
        <input class="input-xlarge" type="text" id="inputTitle" placeholder="Title" name="event[title]" value="<%= @event.title %>">

        <label for="inputLocation">Location</label>
        <input class="input-xlarge" type="text" id="inputLocation" placeholder="Location" name="event[location]" value="<%= @event.location %>">

        <label for="inputDesciption">Description</label>
        <textarea class="input-xxlarge" rows="5" id="inputDesciption" placeholder="Description" name="event[description]"><%= @event.description %></textarea>

      </div>

      <div class="tab-pane" id="Time">

        <legend>Your time proposals</legend>
        <span class="help-block">Click on the dates you would like to choose and select a time to add a new time proposal.</span>
        <div class="row-fluid">
          <div class="span5">
            <ul id="choices" class="unstyled">
              <% @event.choices.each do |choice| 
                formattedStart = choice.start_time.strftime('%l:%M%P %a, %b %e, %Y');
                formattedEnd = choice.end_time.strftime('%l:%M%P %a, %b %e, %Y');
                %>
                <li>
                  <div class="input-prepend span12">
                    <button class="btn" type="button"><i class="icon-trash"></i></button>
                    <div class="input-prepend">
                      <div>
                        <input type="text" disabled value="<%= formattedStart %>">
                        <input class="choice-start" type="hidden" value="<%= choice.start_time %>">
                      </div>
                      <div style="display:none;">
                        <input type="text" disabled value="<%= formattedEnd %>">
                        <input class="choice-end" type="hidden" value="<%= choice.end_time %>">
                      </div>
                    </div>
                  </div>
                </li>
              <% end %>
            </ul>
          </div>
          <div id="calendar" class="span7"></div>
        </div>

      </div>

      <div class="tab-pane" id="Invite">
        <legend>Invitation information</legend>

        <label for="inputEmails">Emails</label>
        <textarea class="input-xxlarge" rows="5" id="inputEmails" placeholder="Emails you would like to send." name="event[emails]"><%= @event.emails %></textarea>
        <span class="help-block">Separate multiple e-mail recipients by commas(,).</span>

        <button type="submit" class="btn">Finish</button>

      </div>

    </div>

  </div>

</form>

app/views/events/index.html.erb
<%= javascript_include_tag params[:controller] %>
<div id="pollsSubHeader">
	<h3>Create new poll</h3>
	<div id="buttonContainer">
		<div id="scheduleButton">
			<img src="/assets/schedule.png" style="width:70px; padding-right:20px;">
			<a class="btn btn-info" href="/events/new">Schedule an event</a>
		</div>
	</div>
</div>
<div class="headerDivider"></div>
<div>
	<h3>Your polls</h3>
	<table id="tableLaunched"class="table table-hover" style="width:940px; table-layout:fixed;">
		<thead>
			<tr>
				<th style="width:25px;"></th>
				<th style="width:300px;">Subject</th>
				<th style="width:150px;">Participants</th>
				<th style="width:200px;">Latest activity</th>
				<th></th>
			</tr>
		</thead>

		<tbody>
		<%
		count = 0 
		@launched_events.each do |event| 
			if count < 4
				if event.is_closed %>
				<tr class="warning">
					<td><i class="icon-ok"></i></td>
			<% else %>
				<tr class="success">
					<td><i class="icon-time"></i></td>
			<% end
			else
				if event.is_closed %>
				<tr class="warning launched-more">
					<td><i class="icon-ok"></i></td>
			<% else %>
				<tr class="success launched-more">
					<td><i class="icon-time"></i></td>
			<% end
			end %>

					<td> <%= link_to event.title, event_path(event) %> </td>
					<td> <%= event.replies.count %> </td>
					<td> <%= time_ago_in_words(event.updated_at) %>&nbsp ago </td>
					<td> <%= link_to "Administer", '/events/' + event.id.to_s + '#admin' %> </td>
				</tr><%
			count += 1;
		end %>
		</tbody>

	</table>
	<% if count > 4 %>
		<Button id="btnMoreLaunched"class="pull-right btn">More</Button>
	<% end %>
</div>

<div>
	<h3>Polls that you have participated in</h3>
	<table id="tableParticipated"class="table table-hover" style="width:940px; table-layout:fixed;">
		<thead>
			<tr>
				<th style="width:25px;"></th>
				<th style="width:300px;">Subject</th>
				<th style="width:150px;">Participants</th>
				<th style="width:200px;">Latest activity</th>
				<th></th>
			</tr>
		</thead>

		<tbody>
		<%
		count = 0 
		@participated_events.each do |event| 
			if count < 4
				if event.is_closed %>
				<tr class="warning">
					<td><i class="icon-ok"></i></td>
			<% else %>
				<tr class="success">
					<td><i class="icon-time"></i></td>
			<% end
			else
				if event.is_closed %>
				<tr class="warning participated-more">
					<td><i class="icon-ok"></i></td>
			<% else %>
				<tr class="success participated-more">
					<td><i class="icon-time"></i></td>
			<% end
			end %>

					<td> <%= link_to event.title, event_path(event) %> </td>
					<td> <%= event.replies.count %> </td>
					<td> <%= time_ago_in_words(event.updated_at) %>&nbsp ago </td>
					<td></td>
				</tr><%
			count += 1;
		end %>
		</tbody>

	</table>
	<% if count > 4 %>
		<Button id="btnMoreParticipated"class="pull-right btn">More</Button>
	<% end %>
</div>

app/views/events/new.html.erb
<%= javascript_include_tag params[:controller] %>

<form id="new_form" class="form" action="/events" method="post">

  <div class="tabbable tabs-left">

    <ul class="nav nav-tabs">
      <li class="active"><a href="#lA" data-toggle="tab">General</a></li>
      <li><a href="#lB" data-toggle="tab">Time</a></li>
      <li><a href="#lC" data-toggle="tab">Invite</a></li>
    </ul>

    <div class="tab-content">

      <div class="tab-pane active" id="lA">

        <legend>General information</legend>

        <label for="inputTitle">Title</label>
        <input class="input-xlarge" type="text" id="inputTitle" placeholder="Title" name="title">

        <label for="inputLocation">Location</label>
        <input class="input-xlarge" type="text" id="inputLocation" placeholder="Location" name="location">

        <label for="inputDesciption">Description</label>
        <textarea class="input-xxlarge" rows="5" id="inputDesciption" placeholder="Description" name="description"></textarea>

      </div>

      <div class="tab-pane" id="lB">

        <legend>Your time proposals</legend>
        <span class="help-block">Click on the dates you would like to choose and select a time range to add a new time proposal.</span>
        <div class="row-fluid">
          <div class="span5">
            <ul id="choices" class="unstyled">
            </ul>
          </div>
          <div id="calendar" class="span7"></div>
        </div>

      </div>

      <div class="tab-pane" id="lC">
        <legend>Invitation information</legend>

        <label for="inputEmails">Emails</label>
        <textarea class="input-xxlarge" rows="5" id="inputEmails" placeholder="Emails you would like to send." name="emails"></textarea>
        <span class="help-block">Separate multiple e-mail recipients by commas(,).</span>

        <button type="submit" class="btn">Finish</button>

      </div>

    </div>

  </div>

</form>

app/views/events/notification.html.erb
<div class="clearfix" style="padding: 35px 24px 0px 24px;">
	<div style="margin-bottom:25px;">		
		<h1 class="green" style="font-weight:normal;">Thanks <%= @reply_name %>,

		</h1>
		<h2 class="green" style="font-weight:normal;">your choices have been submitted.
		</h2>
	</div>
	<div style="margin-bottom:25px;">		
		<a href="/events/<%= @event_id %>" class="btn"> Return to poll </a>
	</div>

	<div style="margin-top:300px; padding-top:15px; border-top: 2px lightgray solid;">
		Is scheduling appointments a pain for you? <a href="/events/new" class="btn btn-large btn-primary" style="margin-left: 20px;">Create your own ToGather poll now</a>
	</div>
</div>

app/views/events/show.html.erb
<%= javascript_include_tag params[:controller] %>

<div style="padding-left:10px;background-color:#f0f0f0">
	<h2><%= @event.title %></h2>
	<div class="clearfix" style="color:#6f6f6f">
		<% if !@is_owner %>
		<div style="float:left;">
			<span>Poll inithiated by <%= @event.user.name %></span>
		</div>

		<% else %>
			<% if @is_closed %>
				<div style="float:left;">
					<span>Poll closed</span>
				</div>
			<% else %>
				<div style="float:left;">
					<a href="/events/<%= @event.id %>/edit">Edit your poll</a>
				</div>
			<% end %>
		<% end %>

		<span style="padding:0 5px; float:left;"> | </span>

		<div style="float:left;" title="<%= @replies_count %> participants">
			<i class="icon-user"></i>
			<span><%= @replies_count %></span>
		</div>

		<span style="padding:0 5px; float:left;"> | </span>

		<div style="float:left;" title="<%= @comments_count %> comments">
			<i class="icon-comment"></i>
			<span><%= @comments_count %></span>
		</div>

		<span style="padding:0 5px; float:left;"> | </span>

		<div style="float:left;" title="latest activity">
			<i class="icon-time"></i>
			<span><%= time_ago_in_words(@latest_activity) %>&nbspago</span>
		</div>
	</div>

	<div class="clearfix" style="padding-top:3px;">
		<span>Where:&nbsp&nbsp&nbsp<%= @event.location%></span>
	</div>

	<div class="clearfix" style="padding-top:22px;">
		<span style="font-size:18px;"><%= @event.description%></span>
	</div>
</div>

<div class="tabbable">
	<ul class="nav nav-tabs" style="padding-top:10px; background-color:#f0f0f0; font-size:18px;">
		<li class="active"><a href="#choices" data-toggle="tab">choices</a></li>
		<% if @is_owner %>
		<li><a href="#admin" data-toggle="tab">administration</a></li>
		<% end %>
	</ul>
	<div class="tab-content" style="padding-left:10px;">
		<div class="tab-pane active" id="choices">
			<% if !@is_closed %>
				<% if @is_owner %>
					<div style="float:right; margin-bottom:5px;">
						<Button id="btnClose" class="btn" type="button">Close poll</Button>
					</div>
				<% end %>
			<% else %>
			<div class="alert alert-info">
				<p style="font-weight:bold;">This event is closed.</p>
				<% if @event.decision.nil? %>
				This event has been closed. Participation is no longer possible.
				<% else %>
				<%= @event.user.name %> chose
				<ul>
					<% @event.decision.choices.each do |choice| %>
					<li>
						<%= choice.start_time.strftime("%A, %b %d, %Y %l:%M%p") %>
					</li>
					<% end %>
				</ul>
				<% end %>
			</div>
			<% end %>
			<form id="show_form" action="/replies" method="post">
				<table id="choices_table" class="table table-bordered">
					<tbody>
						<tr>  <!-- month year head-->
							<th></th>
							<%  
							choices = @event.choices
							i = 0
							if choices.length > 0
								loop do
									tmp = choices[i].start_time
									count = 1

									loop do
										if (i+1 < choices.length) && (tmp.month == choices[i+1].start_time.month) && (tmp.year == choices[i+1].start_time.year)
											count += 1
											i += 1
										else
											break
										end
									end

									%>
									<th colspan="<%= count %>"><%= tmp.strftime("%b")+" "+tmp.year.to_s %></th>
									<%

									if i < choices.length-1
										i += 1
									else 
										break
									end
								end
							end
							%>
						</tr>
						<tr> <!-- day head -->
							<th></th>
							<%  
							choices = @event.choices
							i = 0
							if choices.length > 0
								loop do
									tmp = choices[i].start_time
									count = 1
									loop do
										if (i+1 < choices.length) && (tmp.day == choices[i+1].start_time.day) && (tmp.month == choices[i+1].start_time.month) && (tmp.year == choices[i+1].start_time.year)
											count += 1
											i += 1
										else
											break
										end
									end

									%>
									<th class="day" colspan="<%= count %>"><%= tmp.strftime("%a")+" " + tmp.day.to_s%></th>
									<%

									if i < choices.length-1
										i += 1
									else 
										break
									end
								end
							end
							%>
						</tr>
						<tr> <!-- time head -->
							<th></th>
							<%
							@event.choices.each do |choice|
								%><th class="time" colspan="1"><%= choice.start_time.strftime("%l:%M %P") %></th><%
							end
							%>
						</tr>
						<!-- replies -->
						<%
						@event.replies.each do |reply|
							numbers = Array.new
							reply.choices.each {|choice| numbers.push(choice.number) }
							%>
							<tr>
								<td><span><%= reply.name %></span></td>
								<%
								1.upto(@event.choices.length) do |i|
									if numbers.include?(i)
										%>
										<td class="success"><i class="icon-ok"></i></td>
										<% 
									else 
										%>
										<td class="error"><i class="icon-remove"></i></td>
										<%
									end
								end
								%>
							</tr>
							<%
						end
						%>
						<% if !@is_closed %>
						<tr>
							<td>
								<input id="reply_name" type="text" name="name" maxlength="64" style="height:19px;margin-bottom:0px;padding:2px 6px 2px 6px;width:116px;">
							</td>
							<%
							1.upto(@event.choices.length) do |i|
								%>
								<td>
									<input type="checkbox" name="choices[<%= i %>]">
								</td>
								<%
							end
							%>
						</tr>
						<% end %>
						<tr>
							<td>
							</td>
							<%
							0.upto(@event.choices.length-1) do |i|
								%>
								<td><%= @event.choices[i].replies.length %></td>
								<%
							end
							%>
						</tr>
					</tbody>
				</table>
				<input id="eventID"type="hidden" name="event_id" value="<%= @event.id %>">
				<% if !@is_closed %>
				<div>
					<div style="float:right;">
						<input class="btn" id="cantMakeIt" type="submit" value="Can't make it">
						<input class="btn btn-primary" id="save" type="submit" value="Save">
					</div>
				</div>
				<% end %>
			</form>

			<div id="comment-area">
				<h3><%= @comments_count %> Comments</h3>

				<div class="accordion" id="accordion">
					<div class="accordion-group">
						<div class="accordion-heading">
							<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#addAComment">
								Add a comment
							</a>
						</div>
						<div id="addAComment" class="accordion-body collapse">
							<div class="accordion-inner">					
								<div class="postbox">
									<div class="avatar">
										<% if current_user.nil? %>
											<image src="/assets/default_gravatar.jpg">
										<% else %>
											<%= image_tag current_user.gravatar_url %>
										<% end %>
									</div>

									<form id="comment_form">
										<div class="textarea-wrapper">
											<div id="content" class="textarea" contenteditable="true" tabindex="0" style="overflow: auto; max-height: 350px;">
												<span class="placeholder">Leave a message...</span>
											</div>

											<div class="post-actions">

												<button id="submitComment" type="submit" class="btn">
													<% if current_user.nil? %>
													Post
													<% else %>
													Post as 
													<span><%= current_user.name %></span>
													<% end %>
												</button>
												<% if current_user.nil? %>
												<input id="user_name" name="name" type="text" style="float:right; margin-right: 60px; margin-top:2px;">
												<span style="float:right; padding-top: 5px; margin-right: 10px;">name</span>
												<% end %>
											</div>
										</div>
									</form>
								</div>
							</div>
						</div>
					</div>
				</div>

					<ul id="post-list" class="post-list">		
						<% 1.upto(@comments_count) do |i| %>
						<li class="post">
							<div class="post-content">
								<div class="avatar hovercard">
									<%= image_tag @comments[i-1].user.gravatar_url %>
								</div>

								<div class="post-body">
									<header>

										<span class="publisher-anchor-color">
											<% if @comments[i-1].user.id == 0 %>
												<span> <%= @comments[i-1].user_name %> </span>
											<% else %>
												<span> <%= @comments[i-1].user.name %> </span>
											<% end %>
										</span>

										<span class="bullet" aria-hidden="true">•</span>

										<span class="time-ago" title="<%= @comments[i-1].updated_at %>"><%= time_ago_in_words(@comments[i-1].updated_at) %></span>

									</header>

									<!-- Use message-container to manage visible height of the post message (including media) -->
									<div class="post-message-container">
										<!-- Use message-content to measure post content (including media) -->
										<div>
											<div class="post-message publisher-anchor-color ">
												<%= @comments[i-1].body %>
											</div>
										</div>
									</div>
								</div>
							</div>
						</li>
						<% end %>
					</ul>
				</div>
			</div>

			<% if @is_owner %>
			<div class="tab-pane" id="admin">
				<h3 style="font-weight: normal;">Participation link</h3>
				<input class="input-xlarge" type="text" value="<%= event_url(@event) %>" disabled >

				<div style="margin-top:40px;">
					<% if !@is_closed %>
					<div class="input-prepend" style="width:100%;">
						<span class="add-on icon-ok"></span>
						<Button id="btnClose1"class="btn" type="button">close</Button>
					</div>

					<div class="input-prepend" style="width:100%;">
						<span class="add-on icon-edit"></span>
						<a id="btnEdit" class="btn" href="<%= edit_event_path(@event) %>">edit</a>
					</div>
					<% end %>

					<div class="input-prepend" style="width:100%;">
						<span class="add-on icon-file"></span>
						<Button id="btnDuplicate" class="btn" type="button">duplicate</Button>
					</div>

					<div class="input-prepend" style="width:100%;">
						<span class="add-on icon-trash"></span>
						<Button id="btnDelete" class="btn" type="button">delete</Button>
					</div>
				</div>
			</div>
			<% end %>
		</div>
	</div>

	<div id="closeEventWindow">
		<div>
			<h4 style="font-weight:normal;">Final decision</h4>
		</div>
		<form id="closeEventForm">
			<input type="hidden" name="is_closed" value="true">
			<div id="closeCheckContainer" style="float:left; height: 300px;">
			</div>
			<div style="float:right;">
				<div id="plot"></div>
				<div class="clearfix">
					<div style="float:right;">
						<Button id="cancelCloseEvent" class="btn" >cancel</Button>
						<Button id="submitCloseEvent" type="submit" class="btn btn-primary" >save</Button>
					</div>
				</div>
			</div>
		</form>
	</div>



</div>
<div id="page-cover"></div>